#!/bin/bash
# lib/project.sh - Project initialization and management module for aidd-o

# Project directory
export PROJECT_DIR="${PROJECT_DIR:-./project}"

# Project structure
PROJECT_SUBDIRS=(
    "src"
    "tests"
    "docs"
    "lib"
    "scripts"
    "config"
)

# Initialize project directory structure
init_project() {
    log_info "Initializing project in: $PROJECT_DIR"

    # Create project directory
    ensure_dir "$PROJECT_DIR"

    # Create subdirectories
    for subdir in "${PROJECT_SUBDIRS[@]}"; do
        ensure_dir "$PROJECT_DIR/$subdir"
    done

    # Create .gitkeep files in empty directories
    for subdir in "${PROJECT_SUBDIRS[@]}"; do
        touch "$PROJECT_DIR/$subdir/.gitkeep"
    done

    log_info "Project structure created successfully"
}

# Load specification file
load_spec() {
    local spec_file="$1"

    log_info "Loading specification: $spec_file"

    if ! is_readable "$spec_file"; then
        log_error "Cannot read specification file: $spec_file"
        return 1
    fi

    # Parse spec file (supports YAML and JSON)
    if command_exists yq; then
        export SPEC_TITLE=$(yq e '.title // ""' "$spec_file")
        export SPEC_DESCRIPTION=$(yq e '.description // ""' "$spec_file")
        export SPEC_REQUIREMENTS=$(yq e '.requirements // ""' "$spec_file")
        export SPEC_GOALS=$(yq e '.goals // ""' "$spec_file")
    elif command_exists jq; then
        export SPEC_TITLE=$(jq -r '.title // ""' "$spec_file")
        export SPEC_DESCRIPTION=$(jq -r '.description // ""' "$spec_file")
        export SPEC_REQUIREMENTS=$(jq -r '.requirements // ""' "$spec_file")
        export SPEC_GOALS=$(jq -r '.goals // ""' "$spec_file")
    else
        log_warn "Neither yq nor jq found, using basic parsing"
        export SPEC_TITLE=""
        export SPEC_DESCRIPTION=""
        export SPEC_REQUIREMENTS=""
        export SPEC_GOALS=""
    fi

    log_debug "Spec loaded: title=$SPEC_TITLE"
    return 0
}

# Generate project README
generate_readme() {
    local spec_file="$1"

    log_info "Generating project README"

    cat > "$PROJECT_DIR/README.md" << EOF
# $(basename "$PROJECT_DIR")

$SPEC_DESCRIPTION

## Project Overview

This project was generated by AIDD-O (AI-Driven Development Orchestrator).

## Getting Started

### Prerequisites

- [List prerequisites here]
- [Add more prerequisites]

### Installation

\`\`\`bash
# Clone the repository
git clone <repository-url>
cd $(basename "$PROJECT_DIR")

# Install dependencies
npm install  # or pip install -r requirements.txt
\`\`\`

## Project Structure

\`\`\`
$PROJECT_DIR/
├── src/           # Source code
├── tests/         # Test files
├── docs/          # Documentation
├── lib/           # Libraries
├── scripts/       # Utility scripts
├── config/        # Configuration files
└── README.md      # This file
\`\`\`

## Usage

[Add usage instructions here]

## Development

[Add development instructions here]

## License

[Add license information here]
EOF

    log_info "README.md generated successfully"
}

# Initialize git repository
init_git() {
    log_info "Initializing git repository"

    if [[ -d ".git" ]]; then
        log_warn "Git repository already exists"
        return 0
    fi

    git init
    git add -A
    git commit -m "Initial project structure generated by AIDD-O"

    log_info "Git repository initialized"
}

# Create .gitignore
create_gitignore() {
    log_info "Creating .gitignore"

    cat > "$PROJECT_DIR/.gitignore" << EOF
# Dependencies
node_modules/
.venv/
venv/
__pycache__/
*.pyc
*.pyo

# Build outputs
dist/
build/
*.o
*.a

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Temporary files
tmp/
temp/
*.tmp

# Environment
.env
.env.local
.env.*.local

# Test coverage
coverage/
.nyc_output/

# Misc
*.bak
*.backup
EOF

    log_debug ".gitignore created"
}

# Setup project environment
setup_project() {
    local spec_file="$1"

    log_info "Setting up project environment"

    # Initialize project structure
    init_project

    # Load specification
    if ! load_spec "$spec_file"; then
        return 1
    fi

    # Generate README
    generate_readme "$spec_file"

    # Initialize git if requested
    if [[ "$INIT_GIT" == "true" ]]; then
        init_git
    fi

    # Create .gitignore
    create_gitignore

    log_info "Project setup completed"
    return 0
}

# Validate project structure
validate_project() {
    log_debug "Validating project structure"

    local valid=true

    # Check required directories
    for subdir in "${PROJECT_SUBDIRS[@]}"; do
        if [[ ! -d "$PROJECT_DIR/$subdir" ]]; then
            log_error "Missing required directory: $subdir"
            valid=false
        fi
    done

    # Check README exists
    if [[ ! -f "$PROJECT_DIR/README.md" ]]; then
        log_error "Missing README.md"
        valid=false
    fi

    if $valid; then
        log_info "Project structure is valid"
        return 0
    else
        log_error "Project structure validation failed"
        return 1
    fi
}

# Get project path
get_project_path() {
    local path="$1"
    if [[ -z "$path" ]]; then
        echo "$PROJECT_DIR"
    elif [[ "$path" == /* ]]; then
        echo "$path"
    else
        echo "$PROJECT_DIR/$path"
    fi
}

# Create subdirectory
create_subdir() {
    local subdir="$1"
    local parent="${2:-$PROJECT_DIR}"

    local full_path
    full_path=$(get_project_path "$subdir")
    ensure_dir "$full_path"
}

# List project directories
list_project_dirs() {
    local parent="${1:-$PROJECT_DIR}"

    if [[ -d "$parent" ]]; then
        find "$parent" -maxdepth 1 -type d -not -path "$parent" -not -name ".*" | sort
    fi
}

# Get project stats
get_project_stats() {
    log_debug "Getting project statistics"

    local file_count=0
    local dir_count=0
    local total_size=0

    # Count files and directories
    while IFS= read -r -d '' item; do
        if [[ -f "$item" ]]; then
            file_count=$((file_count + 1))
            total_size=$((total_size + $(file_size "$item")))
        elif [[ -d "$item" ]]; then
            dir_count=$((dir_count + 1))
        fi
    done < <(find "$PROJECT_DIR" -print0 2>/dev/null)

    log_info "Project stats: $file_count files, $dir_count directories, $(format_duration $total_size)"
}
